In [17]:
import pandas as pd

df = pd.read_json('shumei-label.jsonl', lines =True)

In [18]:
df

,img,width,height,pilmode,phash,alt,riskLevel,riskLabel1,riskLabel2,riskLabel3,riskDescription
0,res/东南亚反动分裂/google_印尼异见人士/00000.jpeg,680,680,RGB,f6c7c9a438c96b89,中国异见人士卢昱宇抵加国获庇护,REJECT,politics,fandongfenlie,yijianrenshi,涉政:反动分裂:异见人士
1,res/东南亚反动分裂/google_印尼异见人士/00001.jpeg,862,485,RGB,91cc366667b36764,中国前特工揭露针对澳洲和海外异见人士的秘密警察行动- ABC News,PASS,normal,,,正常
2,res/东南亚反动分裂/google_印尼异见人士/00002.webp,640,360,RGB,accbd6818109feee,服刑异见人士郭泉的妻儿出走美国- BBC News 中文,PASS,normal,,,正常
3,res/东南亚反动分裂/google_印尼异见人士/00003.jpeg,275,183,RGB,dad1156beb113c74,因帮助海外异见人士四人被香港警方带走| 国安法| 抓捕| 林朗彦| 大纪元,PASS,normal,,,正常
4,res/东南亚反动分裂/google_印尼异见人士/00004.jpeg,290,174,RGB,cc1c33333fe03cc7,蓬佩奥：中国异见人士最清楚中共的残暴| 中共残暴| 大纪元,PASS,normal,,,正常
...,...,...,...,...,...,...,...,...,...,...,...
153626,res/领导人/google_领导人挂像/00197.jpeg,250,352,RGB,8a887d7f27c564b2,邓小平- 维基百科，自由的百科全书,REJECT,politics,hexinlingdao,dengxiaoping,涉政:核心领导:邓小平
153627,res/领导人/google_领导人挂像/00198.jpeg,299,168,RGB,a9d434a5ad1e6ae9,习近平政府要求教堂取下耶稣像挂上自己的照片和语录- 新·品葱,PASS,normal,,,正常
153628,res/领导人/google_领导人挂像/00199.jpeg,275,183,RGB,d2fdea7a9046d238,报道称朝鲜再次扣押美国公民- 纽约时报中文网,PASS,normal,,,正常
153629,res/领导人/google_领导人挂像/00200.jpeg,225,225,RGB,bac946d6b91dc3a4,毛主席像装饰画墙画领导人办公室中堂毛泽东画像壁画伟人玄关挂画-Taobao Singapore,REJECT,politics,hexinlingdao,maozedong,涉政:核心领导:毛泽东
153630,res/领导人/google_领导人挂像/00201.jpeg,300,168,RGB,ee0362bc6c809e7f,中亚峰会挂出大唐旗被嘲营造“万邦来朝”假象| 习近平| 西安市| 新唐人电视台,PASS,normal,,,正常

In [19]:
ffff = (df['phash']=="ffffffffffffffff")
df = df[~ffff]

In [20]:
dfd = (
    df[df.duplicated(subset=["phash"], keep=False)]
    .sort_values(["pilmode"], ascending=False, kind="stable")
    .sort_values(["width"], ascending=False, kind="stable")
    .sort_values(["phash"], ascending=False, kind="stable")
)
dfd

,img,width,height,pilmode,phash,alt,riskLevel,riskLabel1,riskLabel2,riskLabel3,riskDescription
54746,res/政治象征/google_民国国旗/00013.jpeg,200,125,RGB,ffff7fff7fffff7f,中華民国,REJECT,politics,shezheng,shezhengjiantu,涉政:涉政:涉政简图
54747,res/政治象征/google_民国国旗/00013.png,200,125,P,ffff7fff7fffff7f,中華民国,REJECT,politics,shezheng,shezhengjiantu,涉政:涉政:涉政简图
51593,res/政治象征/google_拟人化中国国旗/00006.jpeg,534,750,RGB,ffff4248a0a01f3a,国旗 中国 外国 スーツ 擬人化イラスト - No ...,PASS,normal,,,正常
51786,res/政治象征/google_拟人化中国国旗/00192.jpeg,534,750,RGB,ffff4248a0a01f3a,国旗 中国 外国 スーツ 擬人化イラスト - No: 22833301｜無料イラスト・フリー...,PASS,normal,,,正常
51594,res/政治象征/google_拟人化中国国旗/00006.png,189,266,P,ffff4248a0a01f3a,国旗 中国 外国 スーツ 擬人化イラスト - No ...,PASS,normal,,,正常
...,...,...,...,...,...,...,...,...,...,...,...
64592,res/政治象征/google_香港区旗/00112.png,300,168,P,800a2aa0f9fd775f,基本法》網上版區旗出錯紫荊花蕊消失政制局稱轉格式出錯,PASS,normal,,,正常
26978,res/宗教/google_正常宗教/00083.jpeg,810,1080,RGB,80073f447c7e393f,小五-二手小學宗教全要$50/$20@本青衣/葵芳/荔景MTR順豐到付＃先交收優先＃正常使用...,PASS,normal,,,正常
27103,res/宗教/google_正常宗教/00208.jpeg,810,1080,RGB,80073f447c7e393f,小五-二手小學宗教全要$50/$20@本青衣/葵芳/荔景MTR順豐到付＃先交收優先＃正常使用...,PASS,normal,,,正常
97155,res/特殊语种/google_藏语/00035.jpeg,750,1091,RGB,8000ff55857f576e,藏语- 抖音百科,PASS,normal,,,正常
97232,res/特殊语种/google_藏语/00112.jpeg,186,271,RGB,8000ff55857f576e,藏语- 抖音百科,PASS,normal,,,正常

In [21]:
all_modes = df.sort_values(['pilmode'], ascending=False, kind='stable').drop_duplicates(subset=['pilmode'], keep='first')
all_modes

,img,width,height,pilmode,phash,alt,riskLevel,riskLabel1,riskLabel2,riskLabel3,riskDescription
30,res/东南亚反动分裂/google_印尼异见人士/00030.png,1170,722,RGBA,cfd465071f3e21c3,無論薪資高低，印尼人不怕你知道：賺得少怎麼了？生活照樣很開心！｜許詮｜換日線,PASS,normal,,,正常
0,res/东南亚反动分裂/google_印尼异见人士/00000.jpeg,680,680,RGB,f6c7c9a438c96b89,中国异见人士卢昱宇抵加国获庇护,REJECT,politics,fandongfenlie,yijianrenshi,涉政:反动分裂:异见人士
176,res/个人隐私/google_社保卡/00078.png,194,259,P,84364b1fce37e0b5,上海社保卡”APP停止服务，社保卡服务可在 ...,PASS,normal,,,正常
9639,res/反动分裂/google_反共标志/00026.png,1200,630,LA,b3e03f1f1898b731,Charlemagne(SS-WGD) (しゃるるまーにゅ)とは【ピクシブ百科事典】,PASS,normal,,,正常
585,res/个人隐私/google_社保卡/00418.jpeg,336,584,L,954d2ab255f1d07e,提醒！北京暂未开放个人申领第三代社保卡小心诈骗短信_新闻频道_央视网(cctv.com),PASS,normal,,,正常
2102,res/中东政治象征/google_中东国徽/00001.jpeg,1200,1304,CMYK,b3342c669e961cf6,沙特阿拉伯国徽jpg素材图片下载-素材编号04034089-素材天下图库,PASS,normal,,,正常

In [22]:
df = (
    df.sort_values(["pilmode"], ascending=True, kind="stable")
    .sort_values(["width"], ascending=False, kind="stable")
    .sort_values(["phash"], ascending=False, kind="stable")

)
df

,img,width,height,pilmode,phash,alt,riskLevel,riskLabel1,riskLabel2,riskLabel3,riskDescription
48752,res/政治象征/google_国旗/00194.png,250,167,P,ffffffff7fff7fff,世界旗幟| 全球國旗,PASS,normal,,,正常
1351,res/中东反动分裂/google_库尔德区旗/00083.png,266,189,P,ffffffff7f7f7fff,罗贾瓦旗帜- 维基百科，自由的百科全书,PASS,normal,,,正常
130194,res/违禁品/google_彩虹旗/00100.png,225,225,P,ffffff7fffff7f7f,彩虹旗_百度百科,PASS,normal,,,正常
45329,res/政治象征/google_军装/00320.jpeg,852,1280,RGB,ffffe000e7333108,第二次世界大战军装官员- Pixabay上的免费照片- Pixabay,PASS,normal,,,正常
108696,res/裸露/google_其他裸露/00047.jpeg,768,474,RGB,ffffc00094dd1d21,女童上完家教喊「下面痛痛」 母報警怒揪外籍師伸狼爪、受害恐逾2人,PASS,normal,,,正常
...,...,...,...,...,...,...,...,...,...,...,...
37359,res/政治映射/google_维尼熊/00496.jpeg,225,225,RGB,80003fafc526ff3d,大維尼熊娃娃圖片- 海量高清大維尼熊娃娃圖片大全- 阿里巴巴,PASS,normal,,,正常
119531,res/裸露/google_足部特写/00132.jpeg,1200,800,RGB,8000120f9fdfe7f7,脚部特写- 有图网_免费的设计素材网,PASS,normal,,,正常
97218,res/特殊语种/google_藏语/00098.jpeg,426,600,RGB,80000fcd4f7f3b7b,中文書 漢蔵語四音格詞研究(孫艶=著) / アブストラクト古書店 / 古本、中古本、古書籍の...,PASS,normal,,,正常
136811,res/违禁品/google_药品/00205.png,640,298,RGBA,80000f772dcaff3f,藥品經銷| 健通醫藥,PASS,normal,,,正常
138836,res/违禁品/google_野生动物制品/00404.jpeg,675,900,RGB,8000044f4f7f7f7f,汕头市城乡规划局原局长朱家栋被控非法收购珍贵、濒危野生动物制品罪与受贿罪、滥用职权罪起诉意见...,PASS,normal,,,正常

In [23]:
dedup = df.drop_duplicates(subset=["phash"], keep="first")
dedup

,img,width,height,pilmode,phash,alt,riskLevel,riskLabel1,riskLabel2,riskLabel3,riskDescription
48752,res/政治象征/google_国旗/00194.png,250,167,P,ffffffff7fff7fff,世界旗幟| 全球國旗,PASS,normal,,,正常
1351,res/中东反动分裂/google_库尔德区旗/00083.png,266,189,P,ffffffff7f7f7fff,罗贾瓦旗帜- 维基百科，自由的百科全书,PASS,normal,,,正常
130194,res/违禁品/google_彩虹旗/00100.png,225,225,P,ffffff7fffff7f7f,彩虹旗_百度百科,PASS,normal,,,正常
45329,res/政治象征/google_军装/00320.jpeg,852,1280,RGB,ffffe000e7333108,第二次世界大战军装官员- Pixabay上的免费照片- Pixabay,PASS,normal,,,正常
108696,res/裸露/google_其他裸露/00047.jpeg,768,474,RGB,ffffc00094dd1d21,女童上完家教喊「下面痛痛」 母報警怒揪外籍師伸狼爪、受害恐逾2人,PASS,normal,,,正常
...,...,...,...,...,...,...,...,...,...,...,...
37359,res/政治映射/google_维尼熊/00496.jpeg,225,225,RGB,80003fafc526ff3d,大維尼熊娃娃圖片- 海量高清大維尼熊娃娃圖片大全- 阿里巴巴,PASS,normal,,,正常
119531,res/裸露/google_足部特写/00132.jpeg,1200,800,RGB,8000120f9fdfe7f7,脚部特写- 有图网_免费的设计素材网,PASS,normal,,,正常
97218,res/特殊语种/google_藏语/00098.jpeg,426,600,RGB,80000fcd4f7f3b7b,中文書 漢蔵語四音格詞研究(孫艶=著) / アブストラクト古書店 / 古本、中古本、古書籍の...,PASS,normal,,,正常
136811,res/违禁品/google_药品/00205.png,640,298,RGBA,80000f772dcaff3f,藥品經銷| 健通醫藥,PASS,normal,,,正常
138836,res/违禁品/google_野生动物制品/00404.jpeg,675,900,RGB,8000044f4f7f7f7f,汕头市城乡规划局原局长朱家栋被控非法收购珍贵、濒危野生动物制品罪与受贿罪、滥用职权罪起诉意见...,PASS,normal,,,正常

In [24]:
df

,img,width,height,pilmode,phash,alt,riskLevel,riskLabel1,riskLabel2,riskLabel3,riskDescription
48752,res/政治象征/google_国旗/00194.png,250,167,P,ffffffff7fff7fff,世界旗幟| 全球國旗,PASS,normal,,,正常
1351,res/中东反动分裂/google_库尔德区旗/00083.png,266,189,P,ffffffff7f7f7fff,罗贾瓦旗帜- 维基百科，自由的百科全书,PASS,normal,,,正常
130194,res/违禁品/google_彩虹旗/00100.png,225,225,P,ffffff7fffff7f7f,彩虹旗_百度百科,PASS,normal,,,正常
45329,res/政治象征/google_军装/00320.jpeg,852,1280,RGB,ffffe000e7333108,第二次世界大战军装官员- Pixabay上的免费照片- Pixabay,PASS,normal,,,正常
108696,res/裸露/google_其他裸露/00047.jpeg,768,474,RGB,ffffc00094dd1d21,女童上完家教喊「下面痛痛」 母報警怒揪外籍師伸狼爪、受害恐逾2人,PASS,normal,,,正常
...,...,...,...,...,...,...,...,...,...,...,...
37359,res/政治映射/google_维尼熊/00496.jpeg,225,225,RGB,80003fafc526ff3d,大維尼熊娃娃圖片- 海量高清大維尼熊娃娃圖片大全- 阿里巴巴,PASS,normal,,,正常
119531,res/裸露/google_足部特写/00132.jpeg,1200,800,RGB,8000120f9fdfe7f7,脚部特写- 有图网_免费的设计素材网,PASS,normal,,,正常
97218,res/特殊语种/google_藏语/00098.jpeg,426,600,RGB,80000fcd4f7f3b7b,中文書 漢蔵語四音格詞研究(孫艶=著) / アブストラクト古書店 / 古本、中古本、古書籍の...,PASS,normal,,,正常
136811,res/违禁品/google_药品/00205.png,640,298,RGBA,80000f772dcaff3f,藥品經銷| 健通醫藥,PASS,normal,,,正常
138836,res/违禁品/google_野生动物制品/00404.jpeg,675,900,RGB,8000044f4f7f7f7f,汕头市城乡规划局原局长朱家栋被控非法收购珍贵、濒危野生动物制品罪与受贿罪、滥用职权罪起诉意见...,PASS,normal,,,正常

In [25]:
97155 in dedup.index
51594 in dedup.index

False

In [26]:
dedup[dedup["riskLabel2"] == 'fandongfenlie']

,img,width,height,pilmode,phash,alt,riskLevel,riskLabel1,riskLabel2,riskLabel3,riskDescription
14996,res/反动分裂/google_港独人物/00079.jpeg,600,386,RGB,fffe3708c9892059,又一“乱港分子”周庭也于家中被捕-观察者网,REJECT,politics,fandongfenlie,gangdurenwu,涉政:反动分裂:港独人物
12206,res/反动分裂/google_台独事件/00749.jpeg,1024,683,RGB,fff0d86c2383c4cc,顧立雄接防長陸國防部：台獨與台海和平水火不容- 兩岸- 工商時報,REJECT,politics,fandongfenlie,taidurenwu,涉政:反动分裂:台独人物
108842,res/裸露/google_其他裸露/00192.jpeg,533,800,RGB,fff02e4ebd230225,阿朗壹古道鋼筋裸露遊客被刺傷- 生活- 自由時報電子報,REJECT,politics,fandongfenlie,fandongmeiti,涉政:反动分裂:反动媒体
14664,res/反动分裂/google_港独事件/00576.jpeg,299,168,RGB,ffe0649f113f1846,小粉紅勢力】倫敦唐人街流血事件反映中共借海外華人實現長臂管治？ — RFA 自由亞洲電台粵語部,REJECT,politics,fandongfenlie,gangdushijian,涉政:反动分裂:港独事件
61057,res/政治象征/google_迷彩制服/00078.jpeg,1200,800,RGB,ffd2bc8288649aa7,阿兵哥皮要繃緊了！ 賴清德著迷彩服緊盯漢 ...,REJECT,politics,fandongfenlie,taidurenwu,涉政:反动分裂:台独人物
...,...,...,...,...,...,...,...,...,...,...,...
136936,res/违禁品/google_药品/00330.jpeg,1080,608,RGB,80380fb63f4d3e3b,輝瑞新冠口服藥Paxlovid沒有被納入中國醫保“批准藥品目錄”,REJECT,politics,fandongfenlie,fandongmeitibiaozhi,涉政:反动分裂:反动媒体标志
12782,res/反动分裂/google_台独标志/00026.jpeg,480,270,RGB,802a3c7b75ec6aab,关于“武统”，解放军最新表态给“台独”分子下“最后通牒”_哔哩哔哩_bilibili,REJECT,politics,fandongfenlie,taidushijian,涉政:反动分裂:台独事件
15185,res/反动分裂/google_港独人物/00268.jpeg,906,741,RGB,802300ff7f29db9e,为撑暴纵暴摇旗呐喊抹黑港警“港独”黄秋生黄了-热点-新闻-映象网,REJECT,politics,fandongfenlie,gangdushijian,涉政:反动分裂:港独事件
10934,res/反动分裂/google_反华辱华事件/00304.jpeg,600,375,RGB,801fec33cd333dcc,"辱华了又辱华了，美国说唱歌手李鹏（Lil pump ）辱华了,美华行动起来！突然很好奇不反华...",REJECT,politics,fandongfenlie,yijianrenshi,涉政:反动分裂:异见人士
16997,res/反动分裂/google_疆独标志/00107.jpeg,620,468,RGB,800790ff7f4a817f,美国是疆独恐怖势力的幕后黑手！－乌有之乡,REJECT,politics,fandongfenlie,jiangdushijian,涉政:反动分裂:疆独事件

In [27]:
stat = dedup.groupby(['riskLabel1']).size()
stat

riskLabel1
ban                    3824
blackandwhitelist        17
minor                    78
normal               100492
politics              19335
porn                   4026
star                    310
violence                686
dtype: int64

In [28]:
["zhengchang", "shezheng", "baokong", "weijin", "seqing", "xinggan"]
cls = ["normal", "politics", "porn", "sexy", "ban", "violence", "star", "minor", "blackandwhitelist"]
imap = {c:i for i,c in enumerate(cls)}

In [29]:
import json
from pathlib import Path

root = Path("data/data_tool")

sections = []
count = {}
files = {}

data = {"sections": sections, "count": count, "files": files}

for c in cls:
    section = df[df["riskLabel1"] == c]
    section = section["img"].tolist()

    sections.append(c)

    count[c] = len(section)

    files[c] = section

json.dump(data, open("sections-shumei.json", "w"), indent=2, ensure_ascii=False)

In [30]:
# ann_strs = []

# for i, row in dedup.iterrows():
#     path = row['img']
#     cls = imap[row['riskLabel1']]
#     ann_strs.append(f"{path} {cls}")

# # from sklearn.model_selection import train_test_split

# # train, test = train_test_split(ann_strs, test_size=0.2, random_state=42)
# # open('data_tool_shumei_train.txt', 'w').write("\n".join(train))
# # open('data_tool_shumei_val.txt', 'w').write("\n".join(train))

In [31]:
df[df['phash'] == 'd545e2758ad438db']

,img,width,height,pilmode,phash,alt,riskLevel,riskLabel1,riskLabel2,riskLabel3,riskDescription
5742,res/习近平/google_习近平漫画/00687.jpeg,255,198,RGB,d545e2758ad438db,中国版“查理”政治漫画作者会不会倒霉？(组图) - 时政杂谈- eNewsTree.com ...,REJECT,blackandwhitelist,zidingyitupianneirongheimingdan,heimingdan,黑白名单:自定义图片内容黑名单:黑名单